# -*- coding: utf-8 -*-
"""App_Aya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1blopL_x-fBWoQO7nMJjcV2sg74QZuKu2
"""



# import libs
import streamlit as st
import cv2
import numpy as np
import skimage.io as io
import skimage
import matplotlib.pyplot as plt

#segment using otsu
 # convert the image to grayscale
gray_image = skimage.color.rgb2gray(img)
# blur the image to denoise
blurred_image = skimage.filters.gaussian(gray_image, sigma=1.0)
# perform automatic thresholding
t = skimage.filters.threshold_otsu(blurred_image)
binary_mask = blurred_image > t
selection = img.copy()
selection[~binary_mask] = 0

"""## vars, main page, and sidebar"""

# vars
DEMO_IMAGE = 'demo.png' # a demo image for the segmentation page, if none is uploaded
favicon = 'favicon.png'

# main page
st.set_page_config(page_title='Otsu Segmentation - Aya Even Dar', page_icon = favicon, layout = 'wide', initial_sidebar_state = 'auto')
st.title('Image Segmentation using Otsu method, by Aya Even Dar')

# side bar
st.markdown(
    """
    <style>
    [data-testid="stSidebar"][aria-expanded="true"] . div:first-child{
        width: 350px
    }
    
    [data-testid="stSidebar"][aria-expanded="false"] . div:first-child{
        width: 350px
        margin-left: -350px
    }    
    </style>
    
    """,
    unsafe_allow_html=True,


)

st.sidebar.title('Segmentation Sidebar')
st.sidebar.subheader('Site Pages')

# using st.cache so streamlit runs the following function only once, and stores in chache (until changed)
@st.cache()

# take an image, and return a resized that fits our page
def image_resize(image, width=20, height=20, inter = cv2.INTER_AREA):
    dim = None
    (h,w) = image.shape[:2]
    
    if width is None and height is None:
        return image
    
    if width is None:
        r = width/float(w)
        dim = (int(w*r),height)
    
    else:
        r = width/float(w)
        dim = (width, int(h*r))
        
    # resize the image
    resized = cv2.resize(image, dim, interpolation=inter)
    
    return resized

"""## dropdown menu on the sidebar, to navigate between pages"""

# add dropdown to select pages on left
app_mode = st.sidebar.selectbox('Navigate',
                                  ['About App', 'Segment an Image'])

"""## About page"""

# About page
if app_mode == 'About App':
    st.markdown('In this app we will segment images using Otsu method')
    
    
    # side bar
    st.markdown(
        """
        <style>
        [data-testid="stSidebar"][aria-expanded="true"] . div:first-child{
            width: 350px
        }

        [data-testid="stSidebar"][aria-expanded="false"] . div:first-child{
            width: 350px
            margin-left: -350px
        }    
        </style>

        """,
        unsafe_allow_html=True,


    )

    # add a video to the page
    st.video('')


    st.markdown('''
                ## About the app \n
                Try segment your image by Otsu method using this webapp. \n
                Hope you will find it usefull! Aya


                ''')

"""## 'Segment an Image' page"""

# Run image
if app_mode == 'Segment an Image':
    
    st.sidebar.markdown('---') # adds a devider (a line)
    
    # side bar
    st.markdown(
        """
        <style>
        [data-testid="stSidebar"][aria-expanded="true"] . div:first-child{
            width: 350px
        }

        [data-testid="stSidebar"][aria-expanded="false"] . div:first-child{
            width: 350px
            margin-left: -350px
        }    
        </style>

        """,
        unsafe_allow_html=True,


    )

    # read an image from the user
    img_file_buffer = st.sidebar.file_uploader("Upload an image", type=['jpg', 'jpeg', 'png'])

    # assign the uplodaed image from the buffer, by reading it in
    if img_file_buffer is not None:
        image = io.imread(img_file_buffer)
    else: # if no image was uploaded, then segment the demo image
        demo_image = DEMO_IMAGE
        image = io.imread(demo_image)

    # display on the sidebar the uploaded image
    st.sidebar.text('Original Image')
    st.sidebar.image(image)
    
    # call the function to segment the image
    segmented_image = selection
    
    # Display the result on the right (main frame)
    st.subheader('Segmented Image')
    st.image(segmented_image, use_column_width=True)

"""## Deploy to GitHub + Streamlit Cloud

### ipynb to py
"""

from google.colab import drive
drive.mount('/content/drive')

# first remove the markdown cells (because it causes problems in streamlit app)

import nbformat as nbf
folder_path =r'/content/drive/MyDrive/71254_2023/01_Lectures/Class07/kmeans_webapp_yHarris'
ntbk_name_to_convert = 'kmeans.ipynb' # find it in your drive, or upload it to the content
ntbk = nbf.read(f'{folder_path}/kmeans.ipynb', nbf.NO_CONVERT)
new_ntbk = ntbk
new_ntbk.cells = [cell for cell in ntbk.cells if cell.cell_type != "markdown"]
nbf.write(new_ntbk, f'new_{ntbk_name_to_convert}', version=nbf.NO_CONVERT)

# then convert to .py format
!pip install ipython
!pip install nbconvert

# the conversion (it'll save the .py file on the left, in the content)
!ipython nbconvert new_kmeans.ipynb --to python

"""### Create a requirements text file"""

# add more libraries if you used! as a new line
with open('requirements.txt', 'w') as f:
    f.write('''streamlit
scikit-image
opencv-contrib-python-headless
numpy
matplotlib''')